import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/home-page/header";
import HeaderTop from "@/components/home-page/headerTop";
import Footer from "@/components/home-page/footer";
// import { CartProvider } from "@/app/cartContext";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap your layout in CartProvider */}
        {/* <CartProvider> */}
          <HeaderTop />
          <Header />
          {children} {/* Main content will be injected here */}
          <Footer />
        {/* </CartProvider> */}
      </body>
    </html>
  );
}
